# config example.
# see URL: https://github.com/cnphpbb/mysshw/blob/master/readme.md#config
cfg_dir = "./.mysshw.toml"   # default:  $HOME/.mysshw.toml

[sync]
type = "scp" # type: ( scp || github || gitee || Api-http || rpc ) default: scp
remote_uri = "127.0.0.1:22"
username = "root"
password = "$ZK7M@~1RY"
keyPath = ""
passphrase = ""
remote_path = "/data/backup/mysshw/mysshw.toml" # remote file path
access_token = "" # gitee_access_token
gist_id = ""  # gist_id

# config example.
# see URL: https://github.com/cnphpbb/mysshw/blob/master/readme.md#config
[[nodes]]
groups = "Groups01"

[[nodes.ssh]]
alias = 'ğŸš» Test'
host = '127.0.0.1'
name = 'ğŸš» vm-test-1'
password = 'test#Password'
user = 'root'

[[nodes.ssh]]
alias = "all Key"  # å¯ä»¥ç©º, å¯é€‰
name = "ğŸ‘Œ å…¨éƒ¨ Key"
host = "192.168.10.60" # ä¸å¯ä»¥ç©ºï¼Œå¿…é¡»
user ="vm00" # ä¸å¯ä»¥ç©ºï¼Œå¿…é¡»
port = 22  # é»˜è®¤å€¼:22, ä¸å¯ä»¥ç©º, å¦‚æœæ˜¯22ç«¯å£, å¯ä»¥å¿½ç•¥è¿™ä¸ªKEY
password = "" # å¯ä»¥ç©º, å¯é€‰; å¦‚æœæœ‰è¦è‡ªå·±å¡«å¯†ç ï¼Œå¯ä»¥ç©º
#keypath = "~/.ssh/id_rsa" # å¯ä»¥ç©º, å¯é€‰
#passphrase = "abcdefghijklmn" # å¯ä»¥ç©º, å¯é€‰

[[nodes]]
groups = "Groups02"
ssh = [
    # 
	# { name="no ssh conf", alias="", host="192.168.10.60", user="vm00", port=22, password="qwe123!@#qwe", keypath="~/.ssh/id_rsa", passphrase="abcdefghijklmn" },
    { name="vm-test-1", alias="TestNode-1", host="127.0.0.1", user="root", port=22, password="test#Password" },
	{ name="vm-test-2", alias="TestNode", host="127.0.0.1", user="root", port=22, password="test#Password" },
]